// lib/cloudinary.ts

import { v2 as cloudinary } from "cloudinary";

cloudinary.config({
  cloud_name: process.env.CLOUDINARY_CLOUD_NAME,
  api_key: process.env.CLOUDINARY_API_KEY,
  api_secret: process.env.CLOUDINARY_API_SECRET,
  secure: true,
});

type UploadResult = {
  /** Stored in DB, e.g. "reports/uuid.pdf" (public_id + extension) */
  filePath: string;
  /** Direct https URL — only meaningful for public uploads */
  url: string;
};

const uploadBuffer = (
  buffer: Buffer,
  options: Record<string, unknown>,
): Promise<{ public_id: string; secure_url: string }> =>
  new Promise((resolve, reject) => {
    cloudinary.uploader
      .upload_stream(options, (error, result) => {
        if (error || !result) reject(error ?? new Error("Upload failed"));
        else resolve(result);
      })
      .end(buffer);
  });

/**
 * Public upload (prescriptions): the URL is unguessable (UUID filename)
 * and gets embedded in the internal notification email.
 */
export const uploadPublicFile = async (
  file: File,
  folder: string,
  fileName: string,
): Promise<UploadResult> => {
  const buffer = Buffer.from(await file.arrayBuffer());
  const [publicId, extension] = splitExtension(fileName);
  const result = await uploadBuffer(buffer, {
    folder,
    public_id: publicId,
    resource_type: "image",
    format: extension,
    type: "upload",
    overwrite: false,
  });
  return { filePath: `${result.public_id}.${extension}`, url: result.secure_url };
};

/**
 * Private upload (integrity report evidence): only accessible through
 * time-limited signed URLs generated by getPrivateFileUrl().
 */
export const uploadPrivateFile = async (
  file: File,
  folder: string,
  fileName: string,
): Promise<UploadResult> => {
  const buffer = Buffer.from(await file.arrayBuffer());
  const [publicId, extension] = splitExtension(fileName);
  const result = await uploadBuffer(buffer, {
    folder,
    public_id: publicId,
    resource_type: "image",
    format: extension,
    type: "private",
    overwrite: false,
  });
  return { filePath: `${result.public_id}.${extension}`, url: result.secure_url };
};

/** Signed download URL for a private file, valid for `expiresInSeconds`. */
export const getPrivateFileUrl = (
  filePath: string,
  expiresInSeconds = 3600,
): string => {
  const [publicId, extension] = splitExtension(filePath);
  return cloudinary.utils.private_download_url(publicId, extension, {
    resource_type: "image",
    expires_at: Math.floor(Date.now() / 1000) + expiresInSeconds,
  });
};

const splitExtension = (path: string): [string, string] => {
  const dot = path.lastIndexOf(".");
  if (dot === -1) return [path, "bin"];
  return [path.slice(0, dot), path.slice(dot + 1)];
};
